services:
  # comment this out to use local ollama
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  # comment this out to use local pgvector
  pgvector:
    image: 'pgvector/pgvector:pg17'
    environment:
      - 'POSTGRES_DB=spring-pgvector'
      - 'POSTGRES_PASSWORD=pass1234'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5436:5432'
    volumes:
      - pgvector-data:/var/lib/postgresql/data
      - ./src/main/resources/db/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

volumes:
  pgvector-data:
    name: pgvector-data
