services:
  # comment this out to use local ollama
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  # comment this out to use local pgvector
  pgvector:
    image: 'pgvector/pgvector:pg17'
    environment:
      - 'POSTGRES_DB=spring-pgvector'
      - 'POSTGRES_PASSWORD=pass1234'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5436:5432'
    volumes:
      - pgvector-data:/var/lib/postgresql/data
      - ./src/main/resources/db/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

  # Zookeeper - Single instance
  zookeeper1:
    image: 'zookeeper:3.9.3'
    container_name: zookeeper1
    hostname: zookeeper1
    ports:
      - '2181:2181'
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181
#      - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    restart: unless-stopped
    volumes:
      - zookeeper1-data:/data
      - zookeeper1-datalog:/datalog
  # Additional Zookeeper instances (commented out)
  # zookeeper2:
  #   image: 'zookeeper:3.8'
  #   container_name: zookeeper2
  #   hostname: zookeeper2
  #   ports:
  #     - '2182:2181'
  #   environment:
  #     - ZOO_MY_ID=2
  #     - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
  #   volumes:
  #     - zookeeper2-data:/data
  #     - zookeeper2-datalog:/datalog
  # zookeeper3:
  #   image: 'zookeeper:3.8'
  #   container_name: zookeeper3
  #   hostname: zookeeper3
  #   ports:
  #     - '2183:2181'
  #   environment:
  #     - ZOO_MY_ID=3
  #     - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
  #   volumes:
  #     - zookeeper3-data:/data
  #     - zookeeper3-datalog:/datalog

  # Solr Cloud - Single instance
  solr1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solr1
    hostname: solr1
    ports:
      - '8983:8983'
    environment:
      - ZK_HOST=zookeeper1:2181
      - SOLR_HEAP=2g
    volumes:
      - solr1_data:/var/solr/data
      - ./scripts/solr-init.sh:/docker-entrypoint-initdb.d/solr-init.sh
      - ./src/main/resources/test-data.csv:/tmp/test-data.csv
      - ./solr-config/sanity-check:/opt/solr/server/solr/configsets/sanity-check    # testing mount solr configset as volume rather than copy for better test/debug cycling
    depends_on:
      - zookeeper1

  # Additional Solr instance (commented out)
  # solr2:
  #   image: 'solr:9.4'
  #   container_name: solr2
  #   hostname: solr2
  #   ports:
  #     - '8984:8983'
  #   environment:
  #     - ZK_HOST=zookeeper1:2181
  #     - SOLR_HEAP=1g
  #   volumes:
  #     - solr2-data:/var/solr
  #   depends_on:
  #     - zookeeper1
  #    restart: unless-stopped

volumes:
  pgvector-data:
    name: pgvector-data
  zookeeper1-data:
    name: zookeeper1-data
  zookeeper1-datalog:
    name: zookeeper1-datalog
  solr1_data:
  # zookeeper2-data:
  #   name: zookeeper2-data
  # zookeeper2-datalog:
  #   name: zookeeper2-datalog
  # zookeeper3-data:
  #   name: zookeeper3-data
  # zookeeper3-datalog:
  #   name: zookeeper3-datalog
  # solr2-data:
  #   name: solr2-data
