# mixed networking for splitting services across machines
spring:
  application:
    name: spring-pgvector
    port: 8081
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dell:5436/spring-pgvector
    username: postgres
    password: pass1234

  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        chat:
          include: false
      embedding:
        options:
          model: nomic-embed-text     # 768
    vectorstore:
      pgvector:
        dimensions: 768
        index-type: hnsw
        schema-validation: true
        initialize-schema: true
#        remove-existing-vector-store-table: true

  mvc:
    log-request-details: true

logging:
  level:
    root: info
    com.oconeco: info
  pattern:
    console: "%d{MM-dd HH:mm:ss} %highlight(%-5level) [%-40logger{40}]  -- %msg%n"
  file:
    path: logs

solr:
  host: dell
  collection: spring-pgvector
  port: 8983
  # Additional configuration options...
