spring:
  # Development-specific settings
  jpa:
    show-sql: true
  
  # Enable detailed error pages
  server:
    error:
      include-stacktrace: always
      include-message: always
      include-binding-errors: always
      include-exception: true
  
  # Disable template caching for development
  thymeleaf:
    cache: false
    
logging:
  level:
    com.oconeco: debug
    org.springframework.web: info
  pattern:
    console: "%d{MM-dd HH:mm:ss} %highlight(%-5level) [%green(%-40.40logger{39})] %blue(%-25.25M) %yellow(L:%-4L) -- %msg%n"

# Custom application properties
app:
  debug:
    # Filter stack traces to only show application code
    filter-stack-traces: true
    # Package prefixes to include in filtered stack traces
    application-packages:
      - com.oconeco
