server:
  port: 8082      

spring:
  # CSV Import specific settings
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate  # Safer option for imports to prevent accidental schema changes
  
  # Disable web server for import-only operation
  main:
    web-application-type: none
    
logging:
  level:
    com.oconeco: info
    com.oconeco.spring_pgvector.OpportunityCsvImporterRunner: info
    org.springframework.jdbc: info
  pattern:
    console: "%d{MM-dd HH:mm:ss} %highlight(%-5level) [%green(%-40.40logger{39})] -- %msg%n"

# CSV Import specific configuration
app:
  import:
    csv:
      # Maximum number of records to process in a batch
      batch-size: 100
      # Whether to continue on errors or stop
      continue-on-error: true
      # Default delimiter for CSV files
      delimiter: ","

